<?php
/** Plugin Name: Brújula Digital — Catálogo de herramientas
 * Description: CPT, taxonomías y campos base para el catálogo editorial de Brújula Digital.
 * Version: 0.1.0
 */
defined('ABSPATH') || exit;
final class Brujula_Digital_Catalog {
    private const TYPE = 'herramientas'; private const NONCE = 'bd_save_tool';
    public static function boot(): void { add_action('init',[self::class,'register_model']); add_action('add_meta_boxes',[self::class,'add_box']); add_action('save_post_'.self::TYPE,[self::class,'save'],10,2); add_shortcode('brujula_herramienta',[self::class,'shortcode']); }
    public static function register_model(): void { register_post_type(self::TYPE,['labels'=>['name'=>'Herramientas','singular_name'=>'Herramienta','add_new_item'=>'Añadir herramienta','edit_item'=>'Editar herramienta'],'public'=>true,'show_in_rest'=>true,'menu_icon'=>'dashicons-compass','has_archive'=>true,'rewrite'=>['slug'=>'herramientas'],'supports'=>['title','editor','excerpt','thumbnail','revisions']]); foreach(['necesidad'=>'Necesidades','perfil'=>'Perfiles','nivel'=>'Nivel','tipo'=>'Tipos'] as $slug=>$label) register_taxonomy($slug,[self::TYPE],['label'=>$label,'public'=>true,'show_in_rest'=>true,'hierarchical'=>true,'rewrite'=>['slug'=>$slug]]); }
    private static function fields(): array { return ['brand'=>'Marca','one_liner'=>'Frase de utilidad','problem'=>'Problema que resuelve','audience_yes'=>'Para quién sí','audience_no'=>'Para quién no','use_cases'=>'Casos de uso','advantages'=>'Ventajas','limitations'=>'Limitaciones','difficulty'=>'Dificultad','alternatives'=>'Alternativas','price'=>'Precio y fecha de revisión','official_url'=>'URL oficial','affiliate_url'=>'URL afiliada interna','affiliate_status'=>'Estado de afiliación','policy_reviewed'=>'Política revisada el','sources'=>'Fuentes y evidencia','editorial_status'=>'Estado editorial']; }
    public static function add_box(): void { add_meta_box('bd_tool_details','Datos de la herramienta',[self::class,'box'],self::TYPE,'normal','high'); }
    public static function box(WP_Post $post): void { wp_nonce_field(self::NONCE,self::NONCE); foreach(self::fields() as $key=>$label){$v=get_post_meta($post->ID,'_bd_'.$key,true);$area=in_array($key,['use_cases','advantages','limitations','sources'],true);echo '<p><label for="bd_'.$key.'"><strong>'.esc_html($label).'</strong></label>'; if($area) echo '<textarea class="widefat" rows="3" id="bd_'.$key.'" name="bd_'.$key.'">'.esc_textarea($v).'</textarea>'; else echo '<input class="widefat" type="text" id="bd_'.$key.'" name="bd_'.$key.'" value="'.esc_attr($v).'">'; echo '</p>';}}
    public static function save(int $id): void { if(!isset($_POST[self::NONCE])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST[self::NONCE])),self::NONCE)|| (defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)||!current_user_can('edit_post',$id)) return; foreach(array_keys(self::fields()) as $key){$raw=isset($_POST['bd_'.$key])?wp_unslash($_POST['bd_'.$key]):'';$v=in_array($key,['use_cases','advantages','limitations','sources'],true)?sanitize_textarea_field($raw):sanitize_text_field($raw);update_post_meta($id,'_bd_'.$key,$v);}}
    public static function shortcode(): string { $id=get_the_ID(); if(!$id||get_post_type($id)!==self::TYPE)return ''; $get=static fn(string $k)=>(string)get_post_meta($id,'_bd_'.$k,true); ob_start(); ?><article class="bd-tool-card"><p class="bd-tool-kicker"><?php echo esc_html($get('brand')); ?></p><h2><?php echo esc_html(get_the_title($id)); ?></h2><p><?php echo esc_html($get('one_liner')); ?></p><?php if($get('problem')):?><p><strong>Resuelve:</strong> <?php echo esc_html($get('problem')); ?></p><?php endif;?><?php if($get('affiliate_url')):?><a rel="sponsored" href="<?php echo esc_url($get('affiliate_url')); ?>">Comprobar esta herramienta →</a><?php endif;?></article><?php return (string)ob_get_clean(); }
}
Brujula_Digital_Catalog::boot();
